#!/usr/bin/env bash
# Check if an argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Ping the IP address 5 times and format the output
ping_result=$(ping -c 5 "$1")

# Display the ping result
echo "$ping_result" | sed -n '/PING/,/ms/p'
